name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NUGET_AUTH_TOKEN: ${{ secrets.TokenForPackage }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: |
        dotnet restore \
          --source "https://$GITHUB_ACTOR:$NUGET_AUTH_TOKEN@nuget.pkg.github.com/C-Politis/download/vetcheckup.application/index.json" \
          --source "https://$GITHUB_ACTOR:$NUGET_AUTH_TOKEN@nuget.pkg.github.com/C-Politis/download/vetcheckup.domain/index.json" \
          --source "https://$GITHUB_ACTOR:$NUGET_AUTH_TOKEN@nuget.pkg.github.com/C-Politis/download/vetcheckup.infrastructure/index.json" \
          --source "https://api.nuget.org/v3/index.json"

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --configuration Release --no-build --logger trx --results-directory TestResults
