name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x' # Adjust based on your project

    - name: Restore dependencies
      run: dotnet restore --source "https://nuget.pkg.github.com/C-Politis/index.json" --source "https://api.nuget.org/v3/index.json"

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --configuration Release --no-build --logger trx --results-directory TestResults

